[project]
name = "desplitly"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = "./.requirements"




[contracts.dst]
path = "contracts/dst.clar"


[contracts.desplitly]
path = "contracts/desplitly.clar"

[contracts.dst-nft]
path = "contracts/dst-nft.clar"

[contracts.sip-009]
path = "contracts/sip-009.clar"

[contracts.sip-010]
path = "contracts/sip-010.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
